### ISSUE TITLE
Remove GMP dependency

### ISSUE THREAD

**Issue by serieznyi** [consultnn/file-storage#11]
Как на счет того, что бы выпилить эту зависимость? Есть соображения?

**Comment by batyrmastyr** [comment]
Она нужна для работы с уже залитыми файлами (имя в 36-й ситеме счисления). 
Из контрольной суммы можно выпилить почти безболезненно (цена - сброс всего кеша).

Если решим дробить на 16^3 * 16^3 папок вместо нынешних 36^2 * 36^2 - можно будет выпилить.

**Comment by serieznyi** [comment]
@batyrmastyr реализовать обратную совместимость ?
