### ISSUE TITLE
Not correct file extension

### ISSUE THREAD

**Issue by serieznyi** [consultnn/file-storage#3]
fb2 files saved with xml extension. Why?

**Comment by batyrmastyr** [comment]
Cuz it's [xml-based](https://ru.wikipedia.org/wiki/FictionBook)

**Comment by serieznyi** [comment]
@batyrmastyr so, it is not bug? close issue ?

**Comment by batyrmastyr** [comment]
Well, it's a "won't fix" - the only way to fix is to check xml schema and use schema <-> extension map.
Moreover, we have one more similar bug - anything.fb2.gz will loose first extension (fb2)
