### ISSUE TITLE
Add pdf logic

### ISSUE THREAD

**Issue by serieznyi** [consultnn/file-storage#9]
Add logic for process PDF files

**Comment by serieznyi** [comment]
@sokrat @batyrmastyr Wee need this logic? May be I seen it in old project.

**Comment by batyrmastyr** [comment]
Обработка pdf нужна, но я сомневаюсь что эта обработка нужна сразу при загрузке файла, как было на старом.

**Comment by serieznyi** [comment]
@batyrmastyr  ну скорее я предполагал пост обработку при скачивании

Если это не актуально в данный момент, то лучше сменить milestone

**Comment by batyrmastyr** [comment]
Это обработка после загрузки. Актуально даже сейчас, а вот как правильно её сделать - вопрос.
